# Adding entries to this list will enable an item data container whitelist.
# Meaning only items that have a specified persistent data container will render placeholders.
# It's important to note that users will be able to use placeholders on any item using an anvil if this setting isn't used.
# This will still be possible for items that have a persistent data container, so you may want to block anvil use for these items.
whitelisted-persistent-data-containers: []

# Blocks players from using placeholders when renaming an item in an anvil.
block-anvil-placeholders: false

# Do not show result in anvil inventory if it is containing placeholder in name
# Enabling this setting also automatically enables block-anvil-placeholders
block-anvil-placeholders-silently: false

# Message to send when player tries to put placeholder to item's name in anvil
placeholders-are-not-allowed-message: <red>Placeholders are not allowed!


#do not replace any placeholders in item's name
disable-placeholders-in-name: false
#do not replace any placeholders in item's lore
disable-placeholders-in-lore: false

#Server accepts any item changes from players with creative game mode.
#To prevent items corruption, better disable placeholders for players in creative mode
disable-placeholders-for-creative: false