# Adding entries to this list will enable an item data container whitelist.
# Meaning only items that have a specified persistent data container will render placeholders.
# It's important to note that users will be able to use placeholders on any item using an anvil if this setting isn't used.
# This will still be possible for items that have a persistent data container, so you may want to block anvil use for these items.
whitelisted-persistent-data-containers: []

# Blocks players from using placeholders when renaming an item in an anvil.
block-anvil-placeholders: false

#Just remove result item in anvil inventory when name contains placeholder
block-anvil-placeholders-silently: false
  
placeholders-are-not-allowed-message:  "<red>Placeholders are not allowed!"

disable-placeholders-in-name: false
disable-placeholders-in-lore: false